### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by codephilip** [423s22/G1#25]
**Description**:

Team page should include: 

1. Card template of team members.
2. Imported data from DB.

**Comment by emmahaines** [comment]
For each team member's card, where should we put our "about us" small paragraph for you to add onto the pictures, as well as where should we put the pictures we want used?

**Comment by codephilip** [comment]
@emmahaines Thanks, Emma! Please drop the photo, and paragraph in our discord (anywhere).

**Comment by codephilip** [comment]
Team page being completed by @luke5a and @codephilip today.
